global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # сам Prometheus

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']  # контейнер node_exporter

  - job_name: 'custom_mysql_exporter'
    static_configs:
      - targets: ['host.docker.internal:9105']  # ваш MySQL экспортер

  - job_name: 'custom_api_exporter'
    static_configs:
      - targets: ['host.docker.internal:9106']  # ваш API экспортер
